allowBuilds:
  esbuild: true
  sharp: true
  onnxruntime-node: true
  protobufjs: true
  unrs-resolver: false
  '@depot/cli': true
minimumReleaseAgeExclude:
  - '@trigger.dev/build@4.6.1 || 4.6.2'
  - '@trigger.dev/core@4.6.1 || 4.6.2'
  - '@trigger.dev/sdk@4.6.1 || 4.6.2'
  - '@trigger.dev/schema-to-json@4.6.2'
  - trigger.dev@4.6.2
