import { coverArt } from "../../lib/art/cover"
import type { Motif, Palette } from "../../lib/art/palette"
import { Arc } from "./logo"

/**
 * A material's cover. The artwork is generated from the material's own identity
 * (src/lib/art), so it never changes and never needs a photograph.
 *
 * Everything here is server-rendered: the SVG is a string, the type is laid out
 * in CSS, and no JavaScript reaches the browser to draw a card.
 *
 * Sizes come from container query units, so one component works as a 66px
 * thumbnail in a search result and as a 400px cover on a material page,
 * without a single breakpoint.
 */

type Props = {
  seed: string
  look: { motif: Motif; palette: Palette }
  title: string
  topic?: string
  footer?: string
  /** `plate` is the library card, `cover` the larger object on a detail page. */
  variant?: "plate" | "cover"
  className?: string
}

export function Cover({
  seed,
  look,
  title,
  topic,
  footer,
  variant = "plate",
  className = "",
}: Props) {
  const art = coverArt({ motif: look.motif, palette: look.palette, seed })
  const isCover = variant === "cover"

  return (
    <div
      className={`@container relative overflow-hidden rounded-[2px] bg-forest ${
        isCover
          ? "aspect-[3/4] shadow-[0_1px_2px_rgba(20,26,23,.10),0_18px_40px_-22px_rgba(20,26,23,.45)]"
          : "aspect-[4/5]"
      } ${className}`}
    >
      {/* The generated artwork. Ours, deterministic, no user input inside it. */}
      <div
        className="absolute inset-0 [&>svg]:h-full [&>svg]:w-full [&>svg]:object-cover"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: the SVG is generated by src/lib/art from the material's id — never from user input
        dangerouslySetInnerHTML={{ __html: art }}
      />

      {/* A veil, so type stays legible whatever the artwork does underneath. */}
      <div
        className={
          isCover
            ? "absolute inset-0 bg-[linear-gradient(178deg,rgba(12,16,14,.55)_0%,rgba(12,16,14,.10)_32%,rgba(12,16,14,.30)_64%,rgba(12,16,14,.74)_100%)]"
            : "absolute inset-0 bg-[linear-gradient(180deg,rgba(12,16,14,.32)_0%,rgba(12,16,14,0)_30%,rgba(12,16,14,.88)_100%)]"
        }
      />

      <div
        className={`absolute inset-0 flex flex-col text-[#F7F4EE] ${
          isCover ? "items-center p-[7cqw] text-center" : "p-[5.5cqw]"
        }`}
      >
        {isCover ? (
          <>
            <span className="flex flex-col items-center">
              <Arc className="mb-[0.6cqw] h-[3.4cqw] w-[12cqw] text-gold-2" />
              <span className="font-serif text-[8.6cqw] leading-none tracking-[-0.02em]">
                Higherway
              </span>
            </span>
            {topic ? (
              <span className="mt-[1.8cqw] indent-[.34em] text-[2.3cqw] font-medium uppercase tracking-[.34em] text-[rgba(247,244,238,.72)]">
                {topic}
              </span>
            ) : null}
            <h2 className="mt-auto font-serif text-[13cqw] font-light leading-[.98] tracking-[-0.03em]">
              {title}
            </h2>
            <div className="mt-[5cqw] w-full">
              <div className="mb-[3.4cqw] h-px bg-[rgba(247,244,238,.32)]" />
              <span className="indent-[.22em] text-[2.1cqw] font-medium uppercase tracking-[.22em] text-[rgba(247,244,238,.8)]">
                {footer ?? "Faith. Guidance. A brighter tomorrow."}
              </span>
            </div>
          </>
        ) : (
          <>
            <span className="flex items-center gap-[1.8cqw] font-serif text-[5cqw] leading-none tracking-[-0.02em] text-[rgba(247,244,238,.92)]">
              <Arc className="h-[1.9cqw] w-[6cqw] text-gold-2" />
              Higherway
            </span>
            {topic ? (
              <span className="mt-auto indent-[.2em] text-[2.5cqw] font-medium uppercase tracking-[.2em] text-[rgba(247,244,238,.80)]">
                {topic}
              </span>
            ) : (
              <span className="mt-auto" />
            )}
            <h3 className="mt-[2.8cqw] line-clamp-4 font-serif text-[8.4cqw] font-light leading-[1.08] tracking-[-0.025em] break-words">
              {title}
            </h3>
          </>
        )}
      </div>
    </div>
  )
}
