import { coverArt } from "../../lib/art/cover"
import type { Look } from "../../lib/art/palette"
import { titleCase } from "../../lib/text/title-case"
import { Logo } from "./logo"

/**
 * A material's cover — one Higherway publication, drawn the same way everywhere
 * a material appears: library cards, topic shelves, the home page rail, the
 * material's own page, and the admin.
 *
 * It follows the books on the home page, which are the reference for the whole
 * collection: the real logo centred at the head, the title in the archive's
 * serif, a short gold rule, the topic in spaced capitals, and a drawn landscape
 * across the lower half. The larger cover carries the tagline along its foot,
 * as the Latest Addition book does.
 *
 * The artwork is generated from the material's identity and its topic's family
 * (src/lib/art), so it never changes and never needs a photograph. Everything
 * is server-rendered; sizes are container units, so one component works as a
 * search thumbnail and as a standing cover without a breakpoint.
 */

type Props = {
  seed: string
  look: Look
  title: string
  topic?: string
  footer?: string
  /** `plate` is the library card, `cover` the larger object on a detail page. */
  variant?: "plate" | "cover"
  className?: string
}

const TAGLINE = "Faith. Guidance. A brighter tomorrow."

/**
 * Long titles step down, so a four-word title and a fourteen-word one both sit
 * above the landscape rather than the long one running into the hills.
 */
function titleSize(title: string, variant: "plate" | "cover"): string {
  const n = title.length
  if (variant === "cover")
    return n <= 26 ? "text-[10.5cqw]" : n <= 46 ? "text-[9cqw]" : "text-[7.6cqw]"
  return n <= 24 ? "text-[10cqw]" : n <= 44 ? "text-[8.6cqw]" : "text-[7.4cqw]"
}

export function Cover({
  seed,
  look,
  title,
  topic,
  footer,
  variant = "plate",
  className = "",
}: Props) {
  const isCover = variant === "cover"
  const art = coverArt({ look, seed, frame: variant })
  const deep = look.swatch.tone === "deep"

  /**
   * One casing for the whole collection. Normalised for display only — the
   * stored title keeps whatever the publication called it. v1's titles came
   * from filenames, from spreadsheet cells typed by different people and from a
   * few written properly, so a shelf of cards mixed "THE TRIAL OF OUR FAITH"
   * with "A place of surrender". Doing it here covers every cover at once.
   */
  const shown = titleCase(title)
  const Heading = isCover ? "h2" : "h3"

  return (
    <div
      className={`@container relative overflow-hidden rounded-[2px] ${
        deep ? "bg-forest" : "bg-paper-3"
      } ${
        isCover
          ? "aspect-[3/4] shadow-[0_1px_2px_rgba(20,26,23,.10),0_24px_48px_-24px_rgba(20,26,23,.5)]"
          : "aspect-[4/5]"
      } ${className}`}
    >
      {/* The generated artwork. Ours, deterministic, no user input inside it. */}
      <div
        className="absolute inset-0 [&>svg]:h-full [&>svg]:w-full"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: the SVG is generated by src/lib/art from the material's id — never from user input
        dangerouslySetInnerHTML={{ __html: art }}
      />

      {/* The spine: a shadowed band with a line of light where it turns. */}
      <span className="absolute inset-y-0 left-0 w-[3.5%] bg-[linear-gradient(90deg,rgba(20,26,23,.24),rgba(20,26,23,.05))]" />
      <span className="absolute inset-y-0 left-[3.5%] w-px bg-[rgba(255,255,255,.28)]" />

      <div
        className={`absolute inset-x-0 top-0 flex flex-col items-center text-center ${
          isCover ? "px-[9cqw] pt-[9cqw]" : "px-[9cqw] pt-[8cqw]"
        } ${deep ? "text-paper-2" : "text-ink"}`}
      >
        <Logo decorative className={isCover ? "h-[10cqw] w-[27cqw]" : "h-[8.5cqw] w-[23cqw]"} />

        <Heading
          className={`${isCover ? "mt-[6.5cqw]" : "mt-[5cqw]"} line-clamp-3 text-pretty break-words font-serif font-normal leading-[1.04] tracking-[-0.02em] ${titleSize(shown, variant)}`}
        >
          {shown}
        </Heading>

        <span
          className={`${isCover ? "mt-[5cqw] w-[12cqw]" : "mt-[4.5cqw] w-[10cqw]"} h-px bg-gold`}
        />

        {topic ? (
          <span
            className={`${isCover ? "mt-[4.5cqw] text-[3cqw]" : "mt-[3.6cqw] text-[max(7px,3.1cqw)]"} indent-[.3em] font-medium uppercase tracking-[.3em] ${
              deep ? "text-[rgba(251,248,243,.72)]" : "text-ink-2"
            }`}
          >
            {topic}
          </span>
        ) : null}
      </div>

      {isCover ? (
        <span className="absolute inset-x-0 bottom-[6.5cqw] text-center text-[2.3cqw] font-medium uppercase tracking-[.26em] text-[rgba(251,248,243,.85)]">
          {footer ?? TAGLINE}
        </span>
      ) : null}
    </div>
  )
}
