import { heroArt } from "../../../lib/art/hero"
import { Arrow } from "../masthead"
import { BookStack } from "./book-stack"

/**
 * The home page hero: headline and search on the left, a fan of books on the
 * right, over a drawn misty morning.
 *
 * Search is the one call to action. The masthead already carries Library and
 * About, and each book is itself a way into the library, so buttons here would
 * only repeat them.
 *
 * Server-rendered with no client JavaScript. The search is a plain GET form to
 * /library — the same contract as the masthead's search box — so it works
 * before anything hydrates and with scripts turned off.
 *
 * The art is light at the head and forest at the foot, so everything down to
 * the search box is set in ink on mist.
 */
export function Hero() {
  return (
    <section className="relative overflow-hidden">
      <div
        className="absolute inset-0 z-0 [&>svg]:h-full [&>svg]:w-full"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: generated by src/lib/art, no user input
        dangerouslySetInnerHTML={{ __html: heroArt() }}
      />

      <div className="relative z-10 mx-auto grid max-w-(--measure) items-center gap-x-[clamp(24px,4vw,64px)] gap-y-[clamp(40px,6vw,64px)] px-(--gutter) pb-[clamp(56px,7vw,104px)] pt-[clamp(48px,7.5vw,112px)] lg:grid-cols-[minmax(0,1.12fr)_minmax(0,1fr)]">
        <div className="@container">
          <p className="text-[11px] font-medium uppercase tracking-[.22em] text-ink-2">
            Faith. Guidance. A brighter tomorrow.
          </p>
          <h1 className="mt-5 text-[clamp(40px,12.4cqw,92px)] text-ink">
            Wisdom for a{" "}
            <span className="relative inline-block">
              more
              <svg
                viewBox="0 0 200 20"
                preserveAspectRatio="none"
                className="absolute -bottom-[0.04em] left-[-2%] h-[0.15em] w-[104%] text-gold"
                aria-hidden="true"
                focusable="false"
              >
                <path
                  d="M4 13 C 58 5, 132 3, 196 9"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="4"
                  strokeLinecap="round"
                />
                <path
                  d="M18 15 C 70 9, 130 8, 184 12"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.6"
                  strokeLinecap="round"
                  opacity=".55"
                />
              </svg>
            </span>
            <br className="hidden min-[360px]:inline" /> faithful life.
          </h1>
          <p className="mt-6 max-w-[46ch] text-[clamp(15.5px,1.2vw,18px)] leading-relaxed text-ink">
            A collection of inspired teachings, practical insights and biblical perspectives. Every
            material is free to read and free to download.
          </p>

          <form
            action="/library"
            method="get"
            className="mt-8 flex max-w-[620px] items-center rounded-full bg-paper-2 py-1.5 pl-5 pr-1.5 shadow-[0_18px_40px_-22px_rgba(20,26,23,.55)] ring-1 ring-[rgba(20,26,23,.06)] transition-shadow focus-within:ring-2 focus-within:ring-gold"
          >
            <label htmlFor="hero-q" className="sr-only">
              Search the archive
            </label>
            <svg
              viewBox="0 0 24 24"
              className="h-5 w-5 flex-none text-ink-2"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.8"
              strokeLinecap="round"
              aria-hidden="true"
              focusable="false"
            >
              <circle cx="11" cy="11" r="7" />
              <path d="m20 20-3.6-3.6" />
            </svg>
            <input
              id="hero-q"
              name="q"
              type="search"
              placeholder="Search articles, topics or keywords…"
              autoComplete="off"
              className="min-w-0 flex-1 bg-transparent px-3 py-3 text-[16px] text-ink outline-none placeholder:text-ink-3"
            />
            <button
              type="submit"
              aria-label="Search"
              className="grid h-12 w-12 flex-none place-items-center rounded-full bg-ink text-paper-2 transition-colors hover:bg-forest-2 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold"
            >
              <Arrow />
            </button>
          </form>
        </div>

        <BookStack />
      </div>
    </section>
  )
}
