import Link from "next/link"
import { Cover } from "../../components/public/cover"
import { Arrow } from "../../components/public/masthead"
import { MaterialCard } from "../../components/public/material-card"
import { heroArt } from "../../lib/art/hero"
import { archiveStats, recentMaterials, topicList } from "../../server/materials/queries"

/**
 * The home page. Entirely server-rendered — a visitor downloads no application
 * JavaScript to read it.
 *
 * Revalidated rather than rebuilt: the archive changes when an admin adds
 * something, not when the site is deployed.
 */
export const revalidate = 300

export default async function HomePage() {
  const [recent, topics, stats] = await Promise.all([
    recentMaterials(8),
    topicList(12),
    archiveStats(),
  ])

  const latest = recent[0]

  return (
    <>
      <section className="relative overflow-hidden py-[clamp(56px,8vw,104px)]">
        <div
          className="absolute inset-0 z-0 [&>svg]:h-full [&>svg]:w-full [&>svg]:object-cover"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: generated by src/lib/art, no user input
          dangerouslySetInnerHTML={{ __html: heroArt() }}
        />
        <div className="absolute inset-0 z-0 bg-[linear-gradient(96deg,rgba(10,14,12,.88)_0%,rgba(10,14,12,.72)_30%,rgba(10,14,12,.30)_62%,rgba(10,14,12,.06)_100%)]" />

        <div className="relative z-10 mx-auto max-w-(--measure) px-(--gutter) text-paper-2">
          <p className="text-[11px] font-medium uppercase tracking-[.2em] text-[rgba(245,241,234,.6)]">
            Faith. Guidance. A brighter tomorrow.
          </p>
          <h1 className="mt-5 max-w-[14ch] text-[clamp(44px,7.4vw,96px)] text-[#FCFAF5]">
            Wisdom for a more faithful life.
          </h1>
          <p className="mt-6 max-w-[46ch] text-[clamp(15.5px,1.15vw,17.5px)] leading-relaxed text-[rgba(251,248,243,.82)]">
            A collection of inspired teachings, practical insights and biblical perspectives. Every
            material is free to read and free to download.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link
              href="/library"
              className="inline-flex items-center gap-2.5 rounded-full border border-paper-2 bg-paper-2 px-7 py-4 text-[15px] font-medium text-ink transition-colors hover:bg-white"
            >
              Browse the library <Arrow />
            </Link>
            <Link
              href="/about"
              className="inline-flex items-center gap-2.5 rounded-full border border-line-dark px-7 py-4 text-[15px] font-medium text-paper-2 transition-colors hover:border-[rgba(245,241,234,.5)]"
            >
              About Higherway
            </Link>
          </div>
        </div>

        <div className="relative z-10 mx-auto mt-[clamp(44px,7vw,88px)] flex max-w-(--measure) flex-wrap items-center gap-x-[clamp(14px,3vw,34px)] gap-y-2 border-t border-[rgba(251,248,243,.18)] px-(--gutter) pt-6 text-[11px] font-medium uppercase tracking-[.22em] text-[rgba(251,248,243,.62)]">
          <span>Inspire</span>
          <span className="text-[rgba(251,248,243,.3)]">—</span>
          <span>Encourage</span>
          <span className="text-[rgba(251,248,243,.3)]">—</span>
          <span>Build</span>
          <span className="text-[rgba(251,248,243,.3)]">—</span>
          <span>Go further</span>
        </div>
      </section>

      {latest ? (
        <section className="bg-paper-2 py-[clamp(56px,7vw,104px)]">
          <div className="mx-auto grid max-w-(--measure) items-center gap-[clamp(32px,6vw,88px)] px-(--gutter) lg:grid-cols-2">
            <div>
              <p className="text-[11px] font-medium uppercase tracking-[.2em] text-taupe">
                Latest addition
              </p>
              <h2 className="mt-3.5 text-[clamp(34px,5vw,62px)]">{latest.title}</h2>
              <p className="mt-1.5 text-[clamp(26px,3.2vw,40px)] text-taupe">
                {latest.topics[0]?.name ?? "Uncategorised"}
              </p>
              <p className="mt-5 max-w-[52ch] text-[clamp(15.5px,1.15vw,17.5px)] leading-relaxed text-ink-2">
                {latest.summary ??
                  "The most recent material added to the Higherway collection. Open it to read every page, or take the file with you."}
              </p>

              <div className="mt-9 flex gap-[clamp(20px,3vw,44px)] border-t border-line-soft pt-6">
                <div>
                  <div className="font-serif text-[clamp(28px,3vw,38px)] font-light leading-none">
                    {stats.materials}
                  </div>
                  <div className="mt-2 text-[10.5px] font-medium uppercase tracking-[.2em] text-taupe">
                    Materials
                  </div>
                </div>
                <div>
                  <div className="font-serif text-[clamp(28px,3vw,38px)] font-light leading-none">
                    {stats.topics}
                  </div>
                  <div className="mt-2 text-[10.5px] font-medium uppercase tracking-[.2em] text-taupe">
                    Topics
                  </div>
                </div>
                <div>
                  <div className="font-serif text-[clamp(28px,3vw,38px)] font-light leading-none">
                    Free
                  </div>
                  <div className="mt-2 text-[10.5px] font-medium uppercase tracking-[.2em] text-taupe">
                    To download
                  </div>
                </div>
              </div>

              <Link
                href={`/m/${latest.slug}`}
                className="mt-8 inline-flex items-center gap-2.5 rounded-full border border-ink bg-ink px-7 py-4 text-[15px] font-medium text-paper-2 transition-colors hover:bg-forest-2"
              >
                Read it <Arrow />
              </Link>
            </div>

            <Link
              href={`/m/${latest.slug}`}
              className="mx-auto w-full max-w-[392px] -rotate-1 transition-transform duration-700 ease-hw-out hover:rotate-0"
              aria-label={`Read ${latest.title}`}
            >
              <Cover
                variant="cover"
                seed={latest.slug}
                look={latest.look}
                title={latest.title}
                topic={latest.topics[0]?.name}
                footer={latest.author ?? undefined}
              />
            </Link>
          </div>
        </section>
      ) : null}

      <section className="py-[clamp(56px,7vw,104px)]">
        <div className="mx-auto max-w-(--measure) px-(--gutter)">
          <div className="mb-[clamp(26px,3vw,40px)] flex items-end justify-between gap-6">
            <div>
              <p className="text-[11px] font-medium uppercase tracking-[.2em] text-taupe">
                Recently added
              </p>
              <h2 className="mt-3 text-[clamp(26px,3.2vw,40px)]">Fresh from the press</h2>
            </div>
            <Link
              href="/library"
              className="inline-flex flex-none items-center gap-2 border-b border-line pb-[3px] text-[13px] font-medium transition-all hover:gap-3 hover:border-ink"
            >
              View all <Arrow />
            </Link>
          </div>

          <div className="grid grid-cols-2 gap-x-4 gap-y-7 sm:grid-cols-3 lg:grid-cols-4">
            {recent.slice(0, 8).map((material) => (
              <MaterialCard key={material.id} material={material} />
            ))}
          </div>
        </div>
      </section>

      {topics.length > 0 ? (
        <section className="py-[clamp(40px,5vw,72px)]">
          <div className="mx-auto max-w-(--measure) px-(--gutter)">
            <div className="mb-[clamp(26px,3vw,40px)] flex items-end justify-between gap-6">
              <div>
                <p className="text-[11px] font-medium uppercase tracking-[.2em] text-taupe">
                  Browse by topic
                </p>
                <h2 className="mt-3 text-[clamp(26px,3.2vw,40px)]">Find what you need</h2>
              </div>
            </div>

            <div className="grid gap-px border-y border-line-soft bg-line-soft sm:grid-cols-2 lg:grid-cols-3">
              {topics.map((topic, i) => (
                <Link
                  key={topic.slug}
                  href={`/topics/${topic.slug}`}
                  className="flex min-h-[170px] flex-col gap-2.5 bg-paper p-[clamp(22px,2.4vw,32px)] transition-colors hover:bg-paper-2"
                >
                  <div className="flex items-center justify-between">
                    <span className="text-[11px] font-medium tracking-[.18em] text-taupe">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <span className="text-[13.5px] text-ink-3">{topic.count}</span>
                  </div>
                  <div className="mt-auto font-serif text-[clamp(22px,2.2vw,28px)] font-light tracking-[-0.02em]">
                    {topic.name}
                  </div>
                  {topic.blurb ? (
                    <p className="text-[13px] leading-relaxed text-ink-3">{topic.blurb}</p>
                  ) : null}
                </Link>
              ))}
            </div>
          </div>
        </section>
      ) : null}

      <section className="bg-forest py-[clamp(56px,7vw,96px)] text-paper-2">
        <div className="mx-auto grid max-w-(--measure) items-end gap-[clamp(28px,5vw,72px)] px-(--gutter) lg:grid-cols-[1.15fr_1fr]">
          <h2 className="max-w-[12ch] text-[clamp(34px,5vw,62px)] text-[#FCFAF5]">
            Same truths. A brighter tomorrow.
          </h2>
          <div>
            <p className="max-w-[44ch] leading-relaxed text-[rgba(251,248,243,.66)]">
              Nothing to sign up for. Pick a topic, open a material, read it through, and take the
              file if it is useful to you.
            </p>
            <Link
              href="/library"
              className="mt-6 inline-flex items-center gap-2.5 rounded-full border border-paper-2 bg-paper-2 px-7 py-4 text-[15px] font-medium text-ink transition-colors hover:bg-white"
            >
              Browse every material <Arrow />
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}
