import Link from "next/link"
import { coverArt } from "../../lib/art/cover"
import { lookFor } from "../../lib/art/palette"
import { Logo } from "../public/logo"

/**
 * The frame around sign-in and invitation pages.
 *
 * Staff pages should feel like the same publication readers see, not a grey
 * administrative panel bolted on the side — so the panel carries the archive's
 * own generated artwork, the same machinery that draws every cover.
 *
 * On a phone the panel becomes a short band with the form rising over it on a
 * rounded sheet, rather than collapsing to nothing.
 */
export function AuthShell({
  children,
  line = "A digital archive of inspired teachings, kept for the church and its friends.",
}: {
  children: React.ReactNode
  line?: string
}) {
  // A fixed seed, so the sign-in page looks the same every time — it is a
  // front door, and a front door should be recognisable.
  const look = lookFor("higherway-sign-in", "faith")
  const art = coverArt({ motif: look.motif, palette: look.palette, seed: "higherway-sign-in" })

  return (
    <div className="flex min-h-screen flex-col lg:grid lg:grid-cols-[1.05fr_1fr]">
      <div className="relative overflow-hidden bg-forest px-6 pb-24 pt-10 lg:flex lg:flex-col lg:justify-between lg:p-14">
        <div
          className="absolute inset-0 opacity-90 [&>svg]:h-full [&>svg]:w-full [&>svg]:object-cover"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: generated by src/lib/art, no user input
          dangerouslySetInnerHTML={{ __html: art }}
        />
        <div className="absolute inset-0 bg-[linear-gradient(160deg,rgba(12,16,14,.72)_0%,rgba(12,16,14,.45)_45%,rgba(12,16,14,.80)_100%)]" />

        {/* The way back out. Someone who reaches sign-in by accident — or who
            signs out and wants the archive again — should not have to edit the
            URL to leave. */}
        <Link
          href="/"
          aria-label="Higherway — home"
          className="relative inline-block transition-opacity hover:opacity-80"
        >
          <Logo className="h-[44px] w-[140px] text-paper-2" />
        </Link>

        <div className="relative mt-10 lg:mt-0">
          <p className="max-w-[24ch] font-serif text-[clamp(26px,3.4vw,40px)] font-light leading-[1.12] tracking-[-0.02em] text-[#FCFAF5]">
            {line}
          </p>
          <p className="mt-6 hidden text-[12px] font-medium uppercase tracking-[.22em] text-[rgba(251,248,243,.55)] lg:block">
            Inspire — Encourage — Build
          </p>
        </div>
      </div>

      <div className="relative z-10 -mt-10 flex flex-1 items-start justify-center rounded-t-[28px] bg-paper px-6 pb-16 pt-12 shadow-[0_-16px_32px_-16px_rgba(20,26,23,0.30)] lg:mt-0 lg:items-center lg:rounded-none lg:px-14 lg:shadow-none">
        <div className="w-full max-w-sm">{children}</div>
      </div>
    </div>
  )
}
